# Hibernate
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/./data/h2-data
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    user: sa
    password: password
    url: jdbc:h2:tcp://localhost/./data/h2-data

springdoc:
  paths-to-match: /**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [%X{traceId}] %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [%X{traceId}] %msg%n"
  ignore:
    uris: ""
  content:
    length:
      limit: 1000
  file:
    path: ./.log
  level:
    root: info

swagger:
  contact-name: Vo Dinh Phuc
  contact-mail: Dinhphuc20092001@gmail.com
  contact-url: https://facebook.com/vdphuc2009
  app-name: Data Visualization API
  app-description: "Develop a crypto trading system with SpringBoot framework and in memory H2 Database."
  app-version: 2.0.0
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0

rest:
  connection:
    timeout:
      millisecond: 15000
  read:
    timeout:
      millisecond: 15000
  api:
    binance:
      endpoint: https://api.binance.com
      path:
        price: /api/v3/ticker/bookTicker
    houbi:
      endpoint: https://api.huobi.pro
      path:
        price: /market/tickers

job:
  fetch-price:
    cron: "*/10 * * * * *"