INSERT INTO user_account (balance, created_date, last_modified_date, created_by, last_modified_by)
VALUES
    (50000.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (50000.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (50000.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (50000.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (50000.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (50000.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (50000.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (50000.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (50000.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (50000.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL);

-- Insert ETHUSDT and BTCUSDT wallets for users 1 to 10
INSERT INTO wallet (user_id, symbol, quantity, created_date, last_modified_date, created_by, last_modified_by)
VALUES
    (1, 'ETHUSDT', 10.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (1, 'BTCUSDT', 2.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (2, 'ETHUSDT', 10.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (2, 'BTCUSDT', 2.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (3, 'ETHUSDT', 10.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (3, 'BTCUSDT', 2.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (4, 'ETHUSDT', 10.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (4, 'BTCUSDT', 2.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (5, 'ETHUSDT', 10.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (5, 'BTCUSDT', 2.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (6, 'ETHUSDT', 10.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (6, 'BTCUSDT', 2.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (7, 'ETHUSDT', 10.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (7, 'BTCUSDT', 2.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (8, 'ETHUSDT', 10.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (8, 'BTCUSDT', 2.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (9, 'ETHUSDT', 10.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (9, 'BTCUSDT', 2.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (10, 'ETHUSDT', 10.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL),
    (10, 'BTCUSDT', 2.0000, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL);
